---
- name: Instanses provisioning
  hosts: localhost
  connection: local
  gather_facts: False


  tasks:
    - name: Make build instance
      ec2_instance:
        name: "Run"
        key_name: "MyKeyPair03"
        instance_type: "t3.micro"
        image_id: ami-092cce4a19b438926
        region: eu-north-1
        network:
          assign_public_ip: yes
        state: present
      register: ec2

    - name: Add build instance to host group
      add_host:
        name: "{{ item.public_ip }}"
        groups: build
      loop: "{{ ec2.instances }}"

- name: Install default-jdk
  hosts: build
  become: yes

  tasks:
    - name: Upgrade all packages to the latest version
      apt:
        name: "*"
        state: latest
        force_apt_get: yes

    - name: Install app
      apt:
        name: default-jdk
        state: present