---
- name: Instanses provisioning
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    instance_type: "t3.micro"
    image: "ami-0c74592590298c864"
      group: "provisioning"
      region: "eu-north-1"

      tasks:
        - name: Make build instance
          ec2: image={{ image }}
            instance_type={{ instance_type }}
            instance_tags='{ "Name":"Build" }'
            region={{ region }}
            group={{ group }}
            wait=true

        - name: Make run instance
            ec2: image={{ image }}
              instance_type={{ instance_type }}
              instance_tags='{ "Name":"Run" }'
              region={{ region }}
              group={{ group }}
              wait=true