---
- name: Instanses provisioning
  hosts: localhost
  gather_facts: False

  tasks:
    - name: Create a security group in AWS
      ec2_group:
        name: default
        description: allow 22 port
        region: eu-north-1
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0

    - name: Make build instance
      ec2_instance:
        name: "Build"
        key_name: "MyKeyPair03"
        instance_type: "t3.micro"
        security_group: default
        network:
          assign_public_ip: true
        image_id: ami-092cce4a19b438926
        region: eu-north-1
      register: myregistry

    - name: Add build instance to host group
      add_host:
        hostname: "{{ item.public_ip_address }}"
        ansible_private_key_file: ~/.ssh/MyKeyPair03.pem
        groups: build
      loop: "{{ myregistry.instances }}"

    - name: Make run instance
      ec2_instance:
        name: "Run"
        key_name: "MyKeyPair03"
        instance_type: "t3.micro"
        security_group: default
        network:
          assign_public_ip: true
        image_id: ami-092cce4a19b438926
        region: eu-north-1
      register: myregistry

    - name: Add build instance to host group
      add_host:
        hostname: "{{ item.public_ip_address }}"
        ansible_private_key_file: ~/.ssh/MyKeyPair03.pem
        groups: run
      loop: "{{ myregistry.instances }}"

- name: Install default-jdk
  hosts: [build,run]
  remote_user: ubuntu
  become_user: root
  become: true

  tasks:

    apt: name={{item}} state=present
    with_items:
      - "*"
      - default-jdk
      - python3
      - python3-pip
      - boto3
      - botocore
    #- name: Update system
      #apt: update_cache=yes

    #- name: Install modules jdk
     # apt:
      #  name: default-jdk
       # state: present

- name: Application building
  hosts: build
  remote_user: ubuntu
  become_user: root
  become: true

  tasks:
    - name: Install git & maven
      apt:
        pkg:
          - git
          - maven

    - name: Directory preparation
      file:
        path: /home/git
        state: directory
        mode: '0777'
      become: yes

    - name: Ensure app was downloaded
      git:
        repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
        dest: /home/git
        clone: yes
        update: yes
        force: yes

    - name: Ensure app was building
      command: mvn package
      become: yes
      args:
        chdir: /home/git/

    - name: PUT war file
      aws_s3:
        bucket: mybacket30.test4.com
        object: hello-1.0.war
        src: /home/git/target/hello-1.0.war
        mode: put

- name: Run application
  hosts: tomcat
  remote_user: ubuntu
  become_user: root
  become: true

  tasks:
    - name: Install Tomcat 9
      apt:
        name: tomcat9
        state: present

    - name: Ensure Tomcat 9 service is started
      service:
        name: tomcat9
        state: started

    - name: GET war file
      aws_s3:
        bucket: mybacket30.test4.com
        object: hello-1.0.war
        dest: /var/lib/tomcat9/webapps/hello-1.0.war
        mode: get

    - name: Application deploing
      service:
        name: tomcat9
        state: restarted