---
- name: Instanses provisioning
  hosts: localhost
  connection: local
  gather_facts: False


  tasks:
    - name: Make run instance
      ec2_instance:
        name: "Run"
        key_name: "MyKeyPair"
        instance_type: "t3.micro"
        image_id: ami-092cce4a19b438926
        region: eu-north-1
        network:
          assign_public_ip: true
        state: present
      register: output
    - name: var
      debug:
        var: output.instances[0].public_ip
    - name: Add build instance to host group
      add_host:
        name: "{{ output.instances[0].public_ip }}"
        groups: build

- name: Install default-jdk
  hosts: build, run
  become: yes

  tasks:
    - name: Upgrade all packages to the latest version
      apt:
        name: "*"
        state: latest
        force_apt_get: yes

    - name: Install app
      apt:
        name: default-jdk
        state: present