---
- name: Instanses provisioning
  hosts: localhost
  gather_facts: False

  tasks:
    - name: Create a security group in AWS
      ec2_group:
        name: default
        description: allow 22 port
        region: eu-north-1
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0

  tasks:
    - name: Make build instance
      ec2_instance:
        name: "Run"
        key_name: "MyKeyPair03"
        instance_type: "t3.micro"
        security_group: default
        network:
          assign_public_ip: true
        image_id: ami-092cce4a19b438926
        region: eu-north-1
      register: myregistry

    - name: Add build instance to host group
      add_host:
        hostname: "{{ item.public_ip_address }}"
        ansible_private_key_file: ~/.ssh/MyKeyPair03.pem
        groups: build
      loop: "{{ myregistry.instances }}"

- name: Install default-jdk
  hosts: build
  remote_user: ubuntu
  become_user: root
  become: true

  tasks:
    - name: Upgrade all packages to the latest version
      apt:
        name: "*"
        state: latest
        force_apt_get: yes

    - name: Install app
      apt:
        name: default-jdk
        state: present