---
- name: Instanses provisioning
  hosts: localhost
  gather_facts: False

  tasks:
    - name: Make build instance
      ec2_instance:
        name: "Build"
        key_name: "MyKeyPair"
        instance_type: t3.micro
        image_id: ami-0c74592590298c864
        region: eu-north-1