pipeline {
  agent any

  stages {

    stage('Terraform') {
      steps {
        sh 'terraform init terraform/'
        sh 'terraform apply --auto-approve terraform/'
          }
        }
      }
}