---
- name: build-server configuration
  hosts: build
  become: yes

  roles:
    - common
    - build

- name: tomcat configuration
  hosts: tomcat
  become: yes

  roles:
    - common
    - tomcat
---